const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const vm = require('node:vm');
function load() { const s = { globalThis: null, Date }; s.globalThis = s; vm.createContext(s); vm.runInContext(fs.readFileSync('js/chapter/chapter-model.js', 'utf8'), s); vm.runInContext(fs.readFileSync('js/chapter/chapter-storage.js', 'utf8'), s); return s.FonlingChapter.Storage; }
function ended(overrides = {}) { return { id: 'c1', name: '第一章', status: 'ended', revision: 3, startedAt: '2026-08-23T01:00:00Z', endedAt: '2026-08-23T02:00:00Z', messages: [{ id: 'u1', role: 'user', speakerName: '主控', content: '出发' }, { id: 'a1', role: 'assistant', speakerName: '阿宁', content: '好' }], rollingSummary: '', rollingSummaryThroughMessageId: '', summary: { confirmedText: '已出发', confirmedAt: '2026-08-23T02:10:00Z', draftStatus: 'none', draftText: '', generatedAt: '', lastFailure: null, sourceSceneText: '' }, ...overrides }; }
test('legacy data initializes optional chapters while preserving summary and messages', () => { const storage = load(); const settings = { summary: '旧摘要' }; const result = storage.migrateCharacterData(settings, [{ id: 'u', role: 'user', content: '旧消息' }]); assert.equal(result.supported, true); assert.deepEqual(Array.from(result.settings.chapters), []); assert.equal(result.settings.summary, '旧摘要'); assert.equal(result.messages[0].chapterId, undefined); assert.equal(settings.chapterSchemaVersion, undefined); });
test('version 1 ownership is normalized and safely serialized', () => { const storage = load(); const settings = { chapterSchemaVersion: 1, chapters: [ended()], activeChapterId: null }; const result = storage.migrateCharacterData(settings, [{ id: 'a1', role: 'assistant', content: '好', chapterId: 'c1' }]); assert.equal(result.supported, true); assert.equal(result.messages[0].chapterId, 'c1'); const serialized = storage.serializeChapterState(result.settings); assert.deepEqual(Object.keys(serialized).sort(), ['activeChapterId', 'chapterSchemaVersion', 'chapters']); });
test('future and structurally invalid chapter data is rejected', () => { const storage = load(); assert.equal(storage.migrateCharacterData({ chapterSchemaVersion: 2 }, []).reason, 'UNSUPPORTED_CHAPTER_SCHEMA'); assert.equal(storage.migrateCharacterData({ chapterSchemaVersion: 1, chapters: [], activeChapterId: 'missing' }, []).supported, false); assert.equal(storage.migrateCharacterData({ chapterSchemaVersion: 1, chapters: [ended(), ended({ name: '重复' })], activeChapterId: null }, []).supported, false); });
test('recent messages reject unknown ownership and archived-content mismatch', () => { const storage = load(); const settings = { chapterSchemaVersion: 1, chapters: [ended()], activeChapterId: null }; assert.equal(storage.migrateCharacterData(settings, [{ id: 'x', role: 'assistant', content: 'x', chapterId: 'missing' }]).reason, 'UNKNOWN_MESSAGE_CHAPTER'); assert.equal(storage.migrateCharacterData(settings, [{ id: 'a1', role: 'assistant', content: '不同', chapterId: 'c1' }]).reason, 'CHAPTER_MESSAGE_MISMATCH'); });
test('recent ownership allows only one final failed-send user outside the active archive', () => {
  const storage = load();
  const endedSettings = { chapterSchemaVersion: 1, chapters: [ended()], activeChapterId: null };
  assert.equal(storage.migrateCharacterData(endedSettings, [{ id: 'ghost', role: 'assistant', content: '幽灵回复', chapterId: 'c1' }]).reason, 'CHAPTER_MESSAGE_NOT_ARCHIVED');
  const activeChapter = { ...ended({ status: 'active', endedAt: '', summary: { confirmedText: '', confirmedAt: '', draftStatus: 'none', draftText: '', generatedAt: '', lastFailure: null, sourceSceneText: '' } }) };
  const activeSettings = { chapterSchemaVersion: 1, chapters: [activeChapter], activeChapterId: 'c1' };
  assert.equal(storage.migrateCharacterData(activeSettings, [{ id: 'pending', role: 'user', content: '待重试', chapterId: 'c1' }]).supported, true);
  assert.equal(storage.migrateCharacterData(activeSettings, [{ id: 'ghost', role: 'assistant', content: '幽灵回复', chapterId: 'c1' }]).reason, 'CHAPTER_MESSAGE_NOT_ARCHIVED');
  assert.equal(storage.migrateCharacterData(activeSettings, [{ id: 'pending', role: 'user', content: '待重试', chapterId: 'c1' }, { id: 'later', role: 'user', content: '后续', chapterId: 'c1' }]).reason, 'CHAPTER_MESSAGE_NOT_ARCHIVED');
});
