const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const vm = require('node:vm');
function load() { const s = { globalThis: null, Date }; s.globalThis = s; vm.createContext(s); vm.runInContext(fs.readFileSync('js/chapter/chapter-model.js', 'utf8'), s); vm.runInContext(fs.readFileSync('js/chapter/chapter-controller.js', 'utf8'), s); return s.FonlingChapter; }
function harness(failSave) { const chapter = load(); let state = { currentCharacter: '阿宁', currentRole: null, messages: [], ...JSON.parse(JSON.stringify(chapter.Model.createEmptyState())) }; let saves = 0; const controller = chapter.Controller.createChapterController({ getState: () => state, replaceState: next => { state = next; }, save: () => { saves += 1; return failSave && saves === 1 ? { ok: false } : { ok: true }; }, now: () => '2026-08-23T01:00:00Z', createId: () => 'c1', getAssistantName: () => '阿宁' }); return { controller, setMessages(messages) { state = { ...state, messages }; }, get state() { return state; } }; }
test('start, rename, cancel persist lifecycle changes', () => { const h = harness(); assert.equal(h.controller.start(' 第一章 ').ok, true); assert.equal(h.controller.rename('c1', '雨夜').ok, true); assert.equal(h.state.chapters[0].name, '雨夜'); assert.equal(h.controller.cancel().ok, true); assert.equal(h.state.chapters.length, 0); });
test('failed save restores complete prior state', () => { const h = harness(true); const before = JSON.stringify(h.state); assert.equal(h.controller.start('失败').ok, false); assert.equal(JSON.stringify(h.state), before); });
test('only owned complete turns archive and mismatches do not write', () => { const h = harness(); h.controller.start('一'); const user = { id: 'u1', role: 'user', content: '问', _roleName: '旅人', chapterId: 'c1' }; const assistant = { id: 'a1', role: 'assistant', content: '答', chapterId: 'c1' }; assert.equal(h.controller.archiveCompletedTurn(user, assistant).ok, true); assert.deepEqual(Array.from(h.state.chapters[0].messages, x => x.id), ['u1', 'a1']); assert.equal(h.state.chapters[0].messages[0].speakerName, '旅人'); assert.equal(h.controller.archiveCompletedTurn({ id: 'u2', role: 'user', content: '章外' }, { id: 'a2', role: 'assistant', content: '章外' }).changed, false); assert.equal(h.controller.archiveCompletedTurn({ id: 'u3', role: 'user', content: '错', chapterId: 'c1' }, { id: 'a3', role: 'assistant', content: '错' }).ok, false); });
test('edit, regenerate, and backtrack synchronize only active transcript', () => { const h = harness(); h.controller.start('一'); h.controller.archiveCompletedTurn({ id: 'u1', role: 'user', content: '问', chapterId: 'c1' }, { id: 'a1', role: 'assistant', content: '答', chapterId: 'c1' }); h.controller.archiveCompletedTurn({ id: 'u2', role: 'user', content: '再问', chapterId: 'c1' }, { id: 'a2', role: 'assistant', content: '再答', chapterId: 'c1' }); assert.equal(h.controller.replaceAssistant('a2', { id: 'a3', content: '重答' }).ok, true); assert.equal(h.controller.canBacktrack({ id: 'a1', role: 'assistant', chapterId: 'c1' }), true); assert.equal(h.controller.canBacktrack({ id: 'x', role: 'assistant' }), false); h.controller.truncateAfter('a1'); assert.deepEqual(Array.from(h.state.chapters[0].messages, x => x.id), ['u1', 'a1']); });
test('end freezes boundary only after a complete turn', () => { const h = harness(); h.controller.start('一'); assert.equal(h.controller.end({ sourceSceneText: '地点：山门' }).ok, false); const user = { id: 'u1', role: 'user', content: '问', chapterId: 'c1' }; const assistant = { id: 'a1', role: 'assistant', content: '答', chapterId: 'c1' }; h.controller.archiveCompletedTurn(user, assistant); h.setMessages([user, assistant]); assert.equal(h.controller.end({ sourceSceneText: '地点：山门' }).ok, true); assert.equal(h.state.activeChapterId, null); assert.equal(h.state.chapters[0].summary.sourceSceneText, '地点：山门'); assert.equal(h.controller.canBacktrack({ id: 'a1', role: 'assistant', chapterId: 'c1' }), false); });
test('an unarchived failed-send tail blocks both cancel and end', () => {
  const empty = harness(); empty.controller.start('一');
  empty.setMessages([{ id: 'u1', role: 'user', content: '失败待重试', chapterId: 'c1' }]);
  assert.equal(empty.controller.cancel().code, 'CHAPTER_PENDING_TURN');
  assert.equal(empty.state.activeChapterId, 'c1');

  const populated = harness(); populated.controller.start('一');
  const user = { id: 'u1', role: 'user', content: '问', chapterId: 'c1' };
  const assistant = { id: 'a1', role: 'assistant', content: '答', chapterId: 'c1' };
  populated.controller.archiveCompletedTurn(user, assistant);
  populated.setMessages([user, assistant, { id: 'u2', role: 'user', content: '失败待重试', chapterId: 'c1' }]);
  assert.equal(populated.controller.end({}).code, 'CHAPTER_PENDING_TURN');
  assert.equal(populated.state.activeChapterId, 'c1');
});
