const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const vm = require('node:vm');
function load() { const s = { globalThis: null, Date }; s.globalThis = s; vm.createContext(s); vm.runInContext(fs.readFileSync('js/chapter/chapter-model.js', 'utf8'), s); return s.FonlingChapter.Model; }
function active(model) { return model.startChapter(model.createEmptyState(), ' 雨夜 ', { id: 'c1', now: '2026-08-23T01:00:00Z' }); }
function withTurn(model) { return model.appendCompletedTurn(active(model), { id: 'u1', role: 'user', content: '出发', _roleName: '旅人' }, { id: 'a1', role: 'assistant', content: '向北走' }, { userSpeakerName: '旅人', assistantSpeakerName: '阿宁' }); }

test('empty state, default naming, and unique active chapter', () => { const m = load(); assert.deepEqual(JSON.parse(JSON.stringify(m.createEmptyState())), { chapterSchemaVersion: 1, chapters: [], activeChapterId: null }); assert.equal(m.nextDefaultName(m.createEmptyState()), '第 1 章'); const s = active(m); assert.equal(s.chapters[0].name, '雨夜'); assert.throws(() => m.startChapter(s, '二'), e => e.code === 'ACTIVE_CHAPTER_EXISTS'); assert.throws(() => m.startChapter(m.createEmptyState(), ' '), e => e.code === 'CHAPTER_NAME_REQUIRED'); });
test('empty active chapter can cancel but populated chapter cannot', () => { const m = load(); assert.equal(m.cancelActiveChapter(active(m)).chapters.length, 0); assert.throws(() => m.cancelActiveChapter(withTurn(m)), e => e.code === 'CHAPTER_NOT_EMPTY'); });
test('complete turns archive plain snapshots and reject duplicate ids', () => { const m = load(); const s = withTurn(m); assert.deepEqual(JSON.parse(JSON.stringify(s.chapters[0].messages)), [{ id: 'u1', role: 'user', speakerName: '旅人', content: '出发' }, { id: 'a1', role: 'assistant', speakerName: '阿宁', content: '向北走' }]); assert.throws(() => m.appendCompletedTurn(s, { id: 'u1', role: 'user', content: '重复' }, { id: 'a2', role: 'assistant', content: '重复' }), e => e.code === 'DUPLICATE_MESSAGE_ID'); });
test('end requires a complete turn and is irreversible', () => { const m = load(); assert.equal(m.canEndActiveChapter(active(m)), false); assert.throws(() => m.endActiveChapter(active(m)), e => e.code === 'CHAPTER_INCOMPLETE'); const ended = m.endActiveChapter(withTurn(m), { now: '2026-08-23T02:00:00Z', sourceSceneText: '地点：山门' }); assert.equal(ended.activeChapterId, null); assert.equal(ended.chapters[0].status, 'ended'); assert.equal(ended.chapters[0].summary.draftStatus, 'generating'); assert.equal(ended.chapters[0].summary.sourceSceneText, '地点：山门'); });
test('rename is allowed after end but transcript mutation is not', () => { const m = load(); const ended = m.endActiveChapter(withTurn(m), { now: '2026-08-23T02:00:00Z' }); assert.equal(m.renameChapter(ended, 'c1', '新名').chapters[0].name, '新名'); assert.throws(() => m.replaceAssistantMessage(ended, 'a1', { id: 'a2', content: '新答' }), e => e.code === 'CHAPTER_ENDED'); });
test('active replacement and truncation preserve the boundary', () => { const m = load(); let s = withTurn(m); s = m.appendCompletedTurn(s, { id: 'u2', role: 'user', content: '再问' }, { id: 'a2', role: 'assistant', content: '再答' }); const replaced = m.replaceAssistantMessage(s, 'a2', { id: 'a3', content: '重答' }); assert.deepEqual(Array.from(replaced.chapters[0].messages, x => x.id), ['u1', 'a1', 'u2', 'a3']); assert.deepEqual(Array.from(m.truncateActiveChapterAfter(replaced, 'a1').chapters[0].messages, x => x.id), ['u1', 'a1']); assert.throws(() => m.truncateActiveChapterAfter(replaced, 'outside'), e => e.code === 'MESSAGE_OUTSIDE_ACTIVE_CHAPTER'); });
test('summary draft never replaces confirmed text until confirmation', () => { const m = load(); let s = m.endActiveChapter(withTurn(m), { now: '2026-08-23T02:00:00Z', sourceSceneText: '场景' }); s = m.setSummaryDraft(s, 'c1', '草稿', '2026-08-23T02:01:00Z'); assert.equal(s.chapters[0].summary.confirmedText, ''); s = m.confirmSummary(s, 'c1', '确认摘要', '2026-08-23T02:02:00Z'); assert.equal(s.chapters[0].summary.confirmedText, '确认摘要'); assert.equal(s.chapters[0].summary.sourceSceneText, ''); s = m.beginSummary(s, 'c1'); s = m.setSummaryDraft(s, 'c1', '替代草稿'); assert.equal(s.chapters[0].summary.confirmedText, '确认摘要'); });
test('normalization rejects duplicate ids and invalid active references', () => { const m = load(); assert.throws(() => m.normalizeState({ chapterSchemaVersion: 1, chapters: [], activeChapterId: 'missing' }), e => e.code === 'INVALID_ACTIVE_CHAPTER'); const c = active(m).chapters[0]; assert.throws(() => m.normalizeState({ chapterSchemaVersion: 1, chapters: [c, { ...c, name: '重复' }], activeChapterId: 'c1' }), e => e.code === 'DUPLICATE_CHAPTER_ID'); });
test('normalization rejects unreachable summary state combinations', () => {
  const m = load(); const source = m.endActiveChapter(withTurn(m), { now: '2026-08-23T02:00:00Z' });
  const noneWithoutConfirmed = JSON.parse(JSON.stringify(source)); noneWithoutConfirmed.chapters[0].summary.draftStatus = 'none';
  assert.throws(() => m.normalizeState(noneWithoutConfirmed), e => e.code === 'INVALID_SUMMARY_STATE');
  const emptyReady = JSON.parse(JSON.stringify(source)); emptyReady.chapters[0].summary.draftStatus = 'ready'; emptyReady.chapters[0].summary.draftText = ' ';
  assert.throws(() => m.normalizeState(emptyReady), e => e.code === 'INVALID_SUMMARY_STATE');
  const activeWithSummary = active(m); activeWithSummary.chapters[0].summary.confirmedText = '不应存在';
  assert.throws(() => m.normalizeState(activeWithSummary), e => e.code === 'INVALID_SUMMARY_STATE');
});
test('interrupted generating summaries recover to a retryable failed state unless their request is still tracked', () => {
  const m = load(); const source = m.endActiveChapter(withTurn(m), { now: '2026-08-23T02:00:00Z' });
  const recovered = m.recoverInterruptedSummaries(source, () => false, '2026-08-23T03:00:00Z');
  assert.equal(recovered.changed, true);
  assert.equal(recovered.state.chapters[0].summary.draftStatus, 'failed');
  assert.equal(recovered.state.chapters[0].summary.lastFailure.code, 'CHAPTER_SUMMARY_INTERRUPTED');
  assert.equal(m.recoverInterruptedSummaries(source, () => true).changed, false);
});
